#override the application context (URL)
#localhost:8080/movies will become localhost:8080/application/movies
server:
  applicationContextPath: /application
#logging redirected to file
logging:
  level: INFO
  appenders:
    - type: file
      currentLogFilename: /Users/udays/myapplication.log
      threshold: ALL
      queueSize: 512
      discardingThreshold: 0
      archive: true
      archivedLogFilenamePattern: /Users/udays/myapplication-%d.log
      archivedFileCount: 5
      timeZone: UTC
      logFormat: "%-5p [%d{ISO8601,UTC}] %c: %m%n%rEx"
      bufferSize: 8KiB
      immediateFlush: true